#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.0.build{build}

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      ARCH: "32"
      
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
      ARCH: "64"

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) # RDP
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda create -n _dtocean_oandm python=%PYTHON_VERSION% pip
  - activate _dtocean_oandm
  - copy .condarc %CONDA_PREFIX%
  - ^
    conda install dtocean-logistics=2.0.0
                  dtocean-economics=2.0.0
                  dtocean-reliability=2.0.0
                  "polite>=0.9,<1"
  - conda install --file requirements-conda-dev.txt
  - pip install -e .
  - conda install mock pytest pytest-cov=2.5.1 pytest-mock
  
build: off
  
test_script:
  - py.test --cov dtocean_maintenance tests
  
after_test:
 - pip install codecov
 - codecov
  